### ISSUE TITLE
move your shell scripts into npm scripts

### ISSUE THREAD

**Issue by jphilipstevens** [ilPikachu/vocaloid-rankings-twitter-bot#28]
Relying on npm scripts gives you the flexibility to not depend on an OS platform (like shell) and the callers do not need to know what libraries you depend on (like forever)

package json docs on npm scripts: https://docs.npmjs.com/files/package.json#scripts

**Comment by ilPikachu** [comment]
It has been fixed in the latest master, dev branch, thank you for the suggestion.
