### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ilPikachu** [ilPikachu/vocaloid-rankings-twitter-bot#45]
Mocha: https://mochajs.org/

**Comment by jphilipstevens** [comment]
Have you decided on what tools to use for testing?

**Comment by ilPikachu** [comment]
> Have you decided on what tools to use for testing?

Hey Jono, I haven't decide the tools used for testing yet since I'm quite busy with school lately, do you have some good recommendations? Thank you :)

**Comment by jphilipstevens** [comment]
Jest is new and getting good adoption.
Mocha/chai is well known and well supported
